export const REDIS_CLIENT = Symbol('REDIS_CLIENT');
export const RATE_LIMIT_OPTIONS = 'RATE_LIMIT_OPTIONS';
export const CDN_CACHE_OPTIONS = 'CDN_CACHE_OPTIONS';
export const INVALIDATE_PRODUCT_CACHE_OPTIONS = 'INVALIDATE_PRODUCT_CACHE_OPTIONS';
export const PRODUCT_SEARCH_CACHE_VERSION_KEY = 'product:search:version';

export const DEFAULT_PRODUCT_CACHE_TTL_SECONDS = Number(process.env.PRODUCT_CACHE_TTL_SECONDS ?? 60);
export const DEFAULT_PRODUCT_SEARCH_CACHE_TTL_SECONDS = Number(process.env.PRODUCT_SEARCH_CACHE_TTL_SECONDS ?? 30);
export const DEFAULT_PRODUCT_NEGATIVE_CACHE_TTL_SECONDS = Number(process.env.PRODUCT_NEGATIVE_CACHE_TTL_SECONDS ?? 10);
export const DEFAULT_PRODUCT_STALE_FALLBACK_TTL_SECONDS = Number(process.env.PRODUCT_STALE_FALLBACK_TTL_SECONDS ?? 300);
export const DEFAULT_SESSION_TTL_SECONDS = Number(process.env.SESSION_TTL_SECONDS ?? 60 * 60 * 24 * 14);
export const DEFAULT_MAX_SESSIONS_PER_USER = Number(process.env.MAX_SESSIONS_PER_USER ?? 10);
export const DEFAULT_RATE_LIMIT_WINDOW_SECONDS = Number(process.env.RATE_LIMIT_WINDOW_SECONDS ?? 60);
export const DEFAULT_RATE_LIMIT_MAX_REQUESTS = Number(process.env.RATE_LIMIT_MAX_REQUESTS ?? 120);
export const DEFAULT_RATE_LIMIT_BAN_THRESHOLD = Number(process.env.RATE_LIMIT_BAN_THRESHOLD ?? 25);
export const DEFAULT_RATE_LIMIT_BAN_SECONDS = Number(process.env.RATE_LIMIT_BAN_SECONDS ?? 300);
export const DEFAULT_LOCAL_EMERGENCY_LIMIT_MAP_MAX = Number(process.env.LOCAL_EMERGENCY_LIMIT_MAP_MAX ?? 10_000);
export const DEFAULT_RATE_LIMIT_BAN_CANARY_PERCENT = Number(process.env.RATE_LIMIT_BAN_CANARY_PERCENT ?? 100);

export const DEFAULT_CDN_S_MAXAGE = Number(process.env.CDN_CACHE_S_MAXAGE ?? 120);
export const DEFAULT_CDN_STALE_WHILE_REVALIDATE = Number(process.env.CDN_CACHE_STALE_WHILE_REVALIDATE ?? 60);
export const DEFAULT_CDN_STALE_IF_ERROR = Number(process.env.CDN_CACHE_STALE_IF_ERROR ?? 600);

export const DEFAULT_CACHE_LOCK_TTL_SECONDS = Number(process.env.CACHE_LOCK_TTL_SECONDS ?? 5);
export const DEFAULT_METRIC_TTL_SECONDS = Number(process.env.PERFORMANCE_METRIC_TTL_SECONDS ?? 60 * 60 * 24 * 7);
export const DEFAULT_QUEUE_MESSAGE_RETENTION_SECONDS = Number(process.env.QUEUE_MESSAGE_RETENTION_SECONDS ?? 60 * 60 * 24);
export const DEFAULT_QUEUE_MAX_PROMOTION_BATCH = Number(process.env.QUEUE_MAX_PROMOTION_BATCH ?? 100);
export const RATE_LIMIT_FAIL_OPEN = (process.env.RATE_LIMIT_FAIL_OPEN ?? 'false').toLowerCase() === 'true';

export const DEFAULT_SLO_MAX_P95_MS = Number(process.env.SLO_MAX_P95_MS ?? 250);
export const DEFAULT_SLO_MAX_P99_MS = Number(process.env.SLO_MAX_P99_MS ?? 600);
export const DEFAULT_SLO_MIN_SUCCESS_RATE = Number(process.env.SLO_MIN_SUCCESS_RATE ?? 0.995);
